[package]
name = "sntpc"
version = "0.5.1"
description = "Library for making SNTP requests"
homepage = "https://github.com/vpetrigo/sntpc"
repository = "https://github.com/vpetrigo/sntpc"
documentation = "https://docs.rs/sntpc"
readme = "README.md"
categories = ["date-and-time", "no-std", "embedded", "asynchronous"]
keywords = ["sntp", "ntp", "sntp-client", "ntp-client"]
license = "BSD-3-Clause"
authors = ["Vladimir Petrigo <vladimir.petrigo@gmail.com>"]
edition = "2021"
autoexamples = false

exclude = [
    ".github/*",
    "CONTRIBUTING.md",
    ".*",
]

[features]
default = ["std", "std-socket"]
std = []
sync = ["dep:miniloop"]
utils = ["std", "dep:chrono", "chrono/clock"]
log = ["dep:log"]
std-socket = []
embassy-socket = ["dep:embassy-net"]
tokio-socket = ["dep:tokio"]
defmt = ["dep:defmt", "embassy-net/defmt"]

[dependencies]
log = { version = "~0.4", optional = true }
chrono = { version = "~0.4", default-features = false, optional = true }
miniloop = { version = "~0.3", optional = true }
embassy-net = { version = ">=0.5,<0.7", features = ["udp", "proto-ipv4", "proto-ipv6", "medium-ip"], optional = true }
tokio = { version = "1", features = ["net"], optional = true }
defmt = { version = "0.3", optional = true }
cfg-if = "~1"

[dev-dependencies]
miniloop = "~0.3"
criterion = "0.5"

[badges]
maintenance = { status = "actively-developed" }

[[bench]]
name = "sync"
harness = false
required-features = ["sync"]

[[bench]]
name = "async"
harness = false
