[package]
name = "example-simple-no-std"
version = "0.2.0"
edition = "2021"
publish = false

[dependencies]
sntpc = { path = "../../sntpc", default-features = false }
miniloop = { version = "0.4.0" }
