[package]
name = "xtask"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
clap = { version = "~4", features = ["derive"] }
anyhow = "1.0"
colored = "3.0.0"
toml = "~0.9"
glob = "~0.3"
